{% set name = "scine-chemoton" %}
{% set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/chemoton/archive/refs/tags/{{ version }}.tar.gz
    sha256: e8f178d1b1f0f6e656949ed5200394f05a7f8ac9f78a14ea531c66d3f1f02527

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -v --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - networkx
    - numpy
    - python >=3.6
    - scine-database-python
    - scine-molassembler
    - scine-utilities-python
    - scipy
    - setproctitle

test:
  imports:
    - scine_chemoton
  requires:
    - pip
  commands:
    - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Software driving the automated exploration of chemical reaction networks
  home: https://scine.ethz.ch/download/chemoton
  dev_url: https://github.com/qcscine/chemoton
  doc_url: https://scine.ethz.ch/static/download/documentation/chemoton/v{{ version }}/py/

extra:
  recipe-maintainers:
    - awvwgk
