{% set name = "scine-chemoton" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/chemoton/archive/refs/tags/{{ version }}.tar.gz
    sha256: 0a6ee225f6c5882e3ab2b030efe6a2b6ff8834b1e80ed44e89dc0293609a9cce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -v --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - networkx
    - numpy
    - python >=3.6
    - scine-database-python
    - scine-molassembler
    - scine-utilities-python
    - scipy
    - setproctitle

test:
  imports:
    - scine_chemoton
  requires:
    - pip
  commands:
    - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Software driving the automated exploration of chemical reaction networks
  home: https://scine.ethz.ch/download/chemoton
  dev_url: https://github.com/qcscine/chemoton
  doc_url: https://scine.ethz.ch/static/download/documentation/chemoton/v{{ version }}/py/

extra:
  recipe-maintainers:
    - awvwgk
